CREATE TABLE IF NOT EXISTS login(
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    HASHED_PASS VARCHAR(1024) NOT NULL,
    PRE_SALT VARCHAR(255) NOT NULL,
    POST_SALT VARCHAR(255) NOT NULL,
    ADMIN BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS results(
    RUN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RUNNER_ID INTEGER NOT NULL,
    FOREIGN KEY (RUNNER_ID) REFERENCES login (USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wolf_results(
    RUN_ID INTEGER NOT NULL,
    POPULATION INTEGER NOT NULL,
    AVG_ATK FLOAT(24) NOT NULL,
    AVG_HP FLOAT(24) NOT NULL,
    AVG_SPD FLOAT(24) NOT NULL,
    FOREIGN KEY (RUN_ID) REFERENCES results (RUN_ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS jaguar_results(
    RUN_ID INTEGER NOT NULL,
    POPULATION INTEGER NOT NULL,
    AVG_ATK FLOAT(24) NOT NULL,
    AVG_HP FLOAT(24) NOT NULL,
    AVG_SPD FLOAT(24) NOT NULL,
    FOREIGN KEY (RUN_ID) REFERENCES results (RUN_ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS deer_results(
    RUN_ID INTEGER NOT NULL,
    POPULATION INTEGER NOT NULL,
    AVG_ATK FLOAT(24) NOT NULL,
    AVG_HP FLOAT(24) NOT NULL,
    AVG_SPD FLOAT(24) NOT NULL,
    FOREIGN KEY (RUN_ID) REFERENCES results (RUN_ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS rabbit_results(
    RUN_ID INTEGER NOT NULL,
    POPULATION INTEGER NOT NULL,
    AVG_ATK FLOAT(24) NOT NULL,
    AVG_HP FLOAT(24) NOT NULL,
    AVG_SPD FLOAT(24) NOT NULL,
    FOREIGN KEY (RUN_ID) REFERENCES results (RUN_ID) ON DELETE CASCADE
);

